# Generated by Django 5.0 on 2025-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
